apiVersion: v1
kind: Service
metadata:
  name: cg-exam-app-service
  labels:
    app: cg-exam-app
spec:
  selector:
    app: cg-exam-app
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 5000   
  type: NodePort
